/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostRouteImport } from './routes/host'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as BecomeHostRouteImport } from './routes/become-host'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageEventIdRouteImport } from './routes/manage.$eventId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsSlugRouteImport } from './routes/hosts.$slug'
import { Route as EventsSlugRouteImport } from './routes/events_.$slug'
import { Route as CheckInEventIdRouteImport } from './routes/check-in_.$eventId'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoute = HostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeHostRoute = BecomeHostRouteImport.update({
  id: '/become-host',
  path: '/become-host',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageEventIdRoute = ManageEventIdRouteImport.update({
  id: '/manage/$eventId',
  path: '/manage/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsSlugRoute = HostsSlugRouteImport.update({
  id: '/hosts/$slug',
  path: '/hosts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events_/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInEventIdRoute = CheckInEventIdRouteImport.update({
  id: '/check-in_/$eventId',
  path: '/check-in/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/check-in': typeof CheckInRoute
  '/events': typeof EventsRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/check-in/$eventId': typeof CheckInEventIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manage/$eventId': typeof ManageEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/check-in': typeof CheckInRoute
  '/events': typeof EventsRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/check-in/$eventId': typeof CheckInEventIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manage/$eventId': typeof ManageEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-host': typeof BecomeHostRoute
  '/check-in': typeof CheckInRoute
  '/events': typeof EventsRoute
  '/host': typeof HostRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/check-in_/$eventId': typeof CheckInEventIdRoute
  '/events_/$slug': typeof EventsSlugRoute
  '/hosts/$slug': typeof HostsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/manage/$eventId': typeof ManageEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-host'
    | '/check-in'
    | '/events'
    | '/host'
    | '/login'
    | '/my-events'
    | '/signup'
    | '/tickets'
    | '/check-in/$eventId'
    | '/events/$slug'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/manage/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-host'
    | '/check-in'
    | '/events'
    | '/host'
    | '/login'
    | '/my-events'
    | '/signup'
    | '/tickets'
    | '/check-in/$eventId'
    | '/events/$slug'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/manage/$eventId'
  id:
    | '__root__'
    | '/'
    | '/become-host'
    | '/check-in'
    | '/events'
    | '/host'
    | '/login'
    | '/my-events'
    | '/signup'
    | '/tickets'
    | '/check-in_/$eventId'
    | '/events_/$slug'
    | '/hosts/$slug'
    | '/invite/$token'
    | '/manage/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeHostRoute: typeof BecomeHostRoute
  CheckInRoute: typeof CheckInRoute
  EventsRoute: typeof EventsRoute
  HostRoute: typeof HostRoute
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  SignupRoute: typeof SignupRoute
  TicketsRoute: typeof TicketsRoute
  CheckInEventIdRoute: typeof CheckInEventIdRoute
  EventsSlugRoute: typeof EventsSlugRoute
  HostsSlugRoute: typeof HostsSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ManageEventIdRoute: typeof ManageEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host': {
      id: '/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof HostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-host': {
      id: '/become-host'
      path: '/become-host'
      fullPath: '/become-host'
      preLoaderRoute: typeof BecomeHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/$eventId': {
      id: '/manage/$eventId'
      path: '/manage/$eventId'
      fullPath: '/manage/$eventId'
      preLoaderRoute: typeof ManageEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$slug': {
      id: '/hosts/$slug'
      path: '/hosts/$slug'
      fullPath: '/hosts/$slug'
      preLoaderRoute: typeof HostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$slug': {
      id: '/events_/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in_/$eventId': {
      id: '/check-in_/$eventId'
      path: '/check-in/$eventId'
      fullPath: '/check-in/$eventId'
      preLoaderRoute: typeof CheckInEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeHostRoute: BecomeHostRoute,
  CheckInRoute: CheckInRoute,
  EventsRoute: EventsRoute,
  HostRoute: HostRoute,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  SignupRoute: SignupRoute,
  TicketsRoute: TicketsRoute,
  CheckInEventIdRoute: CheckInEventIdRoute,
  EventsSlugRoute: EventsSlugRoute,
  HostsSlugRoute: HostsSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  ManageEventIdRoute: ManageEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
